Added new Math functions
ThakeeNathees/miniscript pull request #160
Opened 2021-07-02 16:38 UTC by victorakpan-dev

I added the `log2, hypot, cbrt, gamma, lgamma, erf, erfc` functions. I wrote some tests but that could be followed up

2021-07-02 18:38 UTC, victorakpan-dev commented
@ThakeeNathees I don't know why the test keeps failing. It worked fine on my machine 
`assert(cbrt(27) == 3)`

2021-07-03 15:10 UTC, ThakeeNathees requested changes
Hi, @victorakpan-dev because of the binary approximation of numbers the floating point arithmetic might differ in different systems by a tiny fraction (see python docs for a good explanation here https://docs.python.org/3/tutorial/floatingpoint.html) That's why we check if the difference between the result and the expected value is less than a tiny threshold value.

2021-07-03 15:10 UTC, ThakeeNathees commented on tests/lang/core.pk
> +assert(cbrt(27) == 3)
Use the threshold here as well to resolve the issue.

2021-07-04 11:43 UTC, ThakeeNathees approved these changes
LGTM, @victorakpan-dev thanks for help us improve the math module,

(I'm traveling now and got a bit busy. I'll test this locally and merge it by tomorrow)

2022-03-30 17:43 UTC, ThakeeNathees commented
Hi @victorakpan-dev It's been a long time and the codebase become unmaintained (I've explained here: https://github.com/ThakeeNathees/pocketlang/issues/168#issuecomment-1083429850) anyways thanks for the implementations.

2022-03-30 17:44 UTC, merged